name: mex_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase Dependencies
  firebase_core: ^2.15.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.6.0

  # UI and State Management
  provider: ^6.0.5
  flutter_riverpod: ^2.4.9
  flutter_bloc: ^8.1.3

  # Navigation and Routing
  go_router: ^10.1.1

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

